# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name of country'),
        ),
    ]
