# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20160409_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='locations.Country', verbose_name='Country'),
            preserve_default=False,
        ),
    ]
