# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20160409_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.IntegerField(choices=[(0, 'Asia'), (1, 'Africa'), (2, 'North America'), (3, 'South America'), (4, 'Antarctica'), (5, 'Europe'), (6, 'Australia')], default=5, verbose_name='Continent'),
        ),
    ]
