# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 23:49
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_bleach.models
import model_utils.fields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', versatileimagefield.fields.VersatileImageField(upload_to=b'images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=b'name', unique=True, verbose_name='Slug')),
                ('description', django_bleach.models.BleachField(verbose_name='Description of trip')),
                ('base_price', models.IntegerField(verbose_name='Price')),
                ('space', models.IntegerField(default='The maximum number of guests', verbose_name='Space')),
                ('main_image', versatileimagefield.fields.VersatileImageField(upload_to=b'images/', verbose_name='Image')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locations', models.ManyToManyField(to='locations.Location', verbose_name='Locations')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='trip',
            field=models.ForeignKey(help_text='Trip', on_delete=django.db.models.deletion.CASCADE, to='trips.Trip'),
        ),
    ]
