# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20160409_0008'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='locations',
        ),
        migrations.AddField(
            model_name='trip',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='locations.Location', verbose_name='Location'),
            preserve_default=False,
        ),
    ]
