# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20160409_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='space',
            field=models.PositiveIntegerField(default=10, help_text='The maximum number of guests', verbose_name='Space'),
        ),
    ]
