# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20160430_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='base_price',
            field=models.IntegerField(help_text='Price per each guest', verbose_name='Price'),
        ),
    ]
