# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('second_name', models.CharField(max_length=50, verbose_name='Second name')),
                ('government_id', models.IntegerField(verbose_name='Government ID')),
                ('child', models.BooleanField(help_text='Is a child?', verbose_name='Child')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Quest',
                'verbose_name_plural': 'Quests',
            },
        ),
    ]
