# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quest',
            new_name='Guest',
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': 'Guest', 'verbose_name_plural': 'Guests'},
        ),
    ]
