# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_auto_20160409_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='child',
            field=models.BooleanField(default=False, help_text='Is a child?', verbose_name='Child'),
        ),
    ]
