# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_auto_20160409_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='child',
        ),
    ]
