# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 23:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentform',
            options={'verbose_name': 'Form of payments', 'verbose_name_plural': 'Forms of payments'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='cashier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
