# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('street_number', models.CharField(max_length=10, verbose_name='Street number')),
                ('postcode', models.CharField(max_length=6, verbose_name='Postcode')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('taxpayer_id', models.IntegerField(help_text='Awarded by the government', verbose_name='Taxpayer ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
            },
        ),
    ]
