# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20160409_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='address',
            name='taxpayer_id',
            field=models.IntegerField(verbose_name='Taxpayer ID'),
        ),
    ]
