# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160409_1145'),
        ('users', '0002_auto_20160408_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
