# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.Address', verbose_name='Billing address'),
        ),
    ]
