# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20160428_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.IntegerField(default=250, verbose_name='Value'),
            preserve_default=False,
        ),
    ]
