# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unit_price',
            field=models.IntegerField(help_text='Participation value of each guest', verbose_name='Unit price'),
        ),
    ]
