# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='government_id',
        ),
        migrations.AddField(
            model_name='guest',
            name='document_id',
            field=models.CharField(default='QWAEASI', help_text='Number of governmental document with photo', max_length=50, verbose_name='Government ID'),
            preserve_default=False,
        ),
    ]
