# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20160511_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='document_id',
            field=models.CharField(max_length=50, verbose_name='Number of governmental document with photo'),
        ),
    ]
